[package]
name = "hp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hp"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
rust-htslib = "0.47.0"
rayon = "1.10.0"
